### ISSUE TITLE
Enhancement: Save dimensions and Measures with Bookmarks

### ISSUE THREAD

**Issue by ljhowell** [ClimberAB/ClimberCustomReport#10]
Hello

This is a great extension as I use Qlikview hide columns feature all the time.  Our Users love to pick their own dimensions and measures.  In Qlikview, we use Bookmarks to save the layout.

Is this possible in Qlik Sense with this extension.  Otherwise, the User will have to reseect the fields again and we have over 100 fields to choose.  

Please let me know so I can tell the community as we are migrating over to Qlik Sense.

Thanks
Les

**Comment by ClimberExtensions** [comment]
Hi Les,
thank you for the positive feedback! The extension does not support bookmarks since it does not quite work the way similar solutions are built in QlikView. 
However, you can define several different Master tables and the extension will remember the previous selections you made in an object. Using tags you can also limit which Master tables are shown in a certain instance of the extension object. With that you might be able to create a solution that works for your users? Please do let us know how it works out.

Kind regards

/Michael
