### ISSUE TITLE
 I can't select any table or add dimensions or measures.

### ISSUE THREAD

**Issue by tincholanus14** [ClimberAB/ClimberCustomReport#31]
Hello, how are you?

I downloaded the extension, but I would not be able to use it since I can't select any table or add dimensions or measures.

![image](https://user-images.githubusercontent.com/29313213/26991933-c8be7d6a-4d32-11e7-8bb6-f74bdc879a9a.png)

Would you have some step-by-step instructions to create a custom report? On the web I can not see the images that you attached.

![image](https://user-images.githubusercontent.com/29313213/26992020-1f8e8e28-4d33-11e7-99a1-5b09e803696a.png)

I tried to build the report on the Qlik Sense Desktop 3.1 SR6 and 3.2 SR3 versions and it did not work on any.

I appreciate your response.

Regards!

**Comment by ClimberExtensions** [comment]
Thanks for the feedback and letting us know that the Readme missed screenshots. 
That issue is now fixed and you should be able to follow the instructions.
What you need to do is create Table with all the dimensions and measures you would like to have and then make a Master Item of it. When it's in the Master Items you can remove the table from the sheet and it should show up in the Custom Report Visualization drop down
