### ISSUE TITLE
How to know custom report extension will work with QS JUNE 2017 version ?

### ISSUE THREAD

**Issue by paulyeo11** [ClimberAB/ClimberCustomReport#32]
Hi Sir

Can some one help to confirm the above before custom report addicted user start to upgrade the version to june 2017.

**Comment by ClimberExtensions** [comment]
June 2017 is not released yet but initial testing using the technical preview shows only a small error with the right-click menu that seems to be a new bug in Qlik Sense. (That is of course reported to the Tech preview community.) 

That said, we do not recommend any of our customers to upgrade straight away and if they have critical applications using extensions they should come to us for a proper support agreement rather than using just the Open Source version found here.
