### ISSUE TITLE
Extension error when mashup runs on external server

### ISSUE THREAD

**Issue by gabiQlik** [ClimberAB/ClimberCustomReport#65]
Hello,

I am using ClimberCustomReport and ClimberSelectionBar in my Qlik Sense apps and both extensions work great.

I built a mashup using Climber extensions and if the mashup is hosted on the QlikSense Server, the climber extensions are working flawlessly.

However, when I host/convert the mashup on a custom NodeJS server, all the QlikSense objects are working and run properly, except for the climber extensions.
The error I receive is related to CORS issue, even tough I have set the Virtual Proxy to allow CORS: Access-Control-Allow-Origin: *.
This is the error that appears in Chrome:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

I tried registering the extension, but I was unable to fix the issue.

## Steps to Reproduce
1. Create a mashup using climber custom report
2. use a nodejs server to host the mashup

### Expected behavior
Climber objects should be displayed

### Actual behavior
Climber objects are not displayed

## Environment
```
[ ] Desktop
[X] Enterprise
```

## Versions
Extension version: 2.1.2
Browser: Chrome 67
Qlik Sense: April 2018
Operating system: Windows Server 2012

**Comment by kfsjostrand** [comment]
Hi gabi,
This issue is more related to how you run your NodeJs server and how that communicate with QS than the Climber Custom Report. As you mention this is related to CORS and you need to try to figure out how to set that up. I assume you use ExpressJs and you should probably take a look at this CORS middleware https://github.com/expressjs/cors
Good luck
