### ISSUE TITLE
Climber Report Selecting ALL Master Items

### ISSUE THREAD

**Issue by cueval** [ClimberAB/ClimberCustomReport#71]
On my climber report, all master item tables automatically get added to the report, which I don't want.  I only want to use one of the master item tables.
On the edit menu on the right, under "Select Tags", "All Tables" is selected, but there is no option for anything else.  Shouldn't I be able to select only certain tables?

**Comment by kfsjostrand** [comment]
Hi Cueval,
You are using a version of Climber Custom Report prior to 2.0. 
In versions after 2.0 we made major changes to how you configure the Custom Report and a lot of new features. One of those features is that you can add master items to the Custom Report. 
With 2.0 we also changed the extension id to cl-custom-report so you can install it along side the older versions.  Remember to uninstall the old version after you converted all your objects to the new version to reduce confusion.

If you run QS November 2017 or later we recommend that you upgrade to the latest version. Otherwise you can add a tag e.g. "CustomReport" 'to the master item table/tables you would like to add, then you should be able to see a "CustomReport" as an option in the "Select Tabs" dropdown.
Regards
Karl
