### ISSUE TITLE
Export to XLS invisible

### ISSUE THREAD

**Issue by rgluzman** [ClimberAB/ClimberCustomReport#79]
Hello

I'm using the last version you just upload, with November 2018 Qlik Sense patch 2 and browser Firefox 65.0.1 x64

I've created new report, everything works fine but when I want to export data the option stay invisible, only Export to App is active, all others export options stay grey (invisible)

I can's see any console errors and problem reproduced everytime

Regards

Régis

### Versions
* Extension version:
* Qlik Sense: 
* Browser:  

*Extension version can be found under About in the property panel of the extension in Edit-mode or in the Qlik Sense Dev-hub.*  

### Description
[Description of the issue, please include screenshots]

### Console errors
[Check the console of the browser for errors]  

*Chrome: Ctrl + Shift + J*   
*Internet Explorer: F12, reload the page after, since IE doesn't keep history*  
*Firefox: Ctrl + Shift + K*

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]

**Comment by MichaelClimber** [comment]
Hi, 
thank you for your input! We did a major rebuild of the export feature a while back and exporting to Excel is not available in the free version of the extension since then. However we have added that and a lot of other features in our subscription version. Take a look at http://climberextensions.com and/or send me a message for more details on how to subscribe to the full extension.

Kind regards

Michael
